version: '3.7'

services:
  app:
    container_name: freenom
    init: true
    image: freenom/auto-renew
    build:
      context: .
      target: dev
    command: npm run start
    volumes:
      - .:/build/
      - node_modules:/build/node_modules
    networks:
      - default
      - localnet
    env_file: .env

networks:
  localnet:

volumes:
  build:
  node_modules:
